### ISSUE TITLE
Text for grant proposals

### ISSUE THREAD

**Issue by adina** [swcarpentry/communications#11]
https://github.com/adina/communications/issues/3 Assigned to @adina

**Comment by jduckles** [comment]
@gvwilson Do we have any existing boilerplate from past grants that can be shared? 

I'll pull it together into something coherent if needed. Otherwise lets brainstorm in here what we need and I'll try to help get this started.

**Comment by adina** [comment]
Thanks @jduckles!

**Comment by gvwilson** [comment]
file:///Users/gvwilson/s/site/blog/2012/01/sloan-foundation-grant-to-software-carpentry-and-mozilla.html 
and 
http://software-carpentry.org/blog/2013/07/sloan-proposal-round-2.html 
are the full text of the Sloan Foundation proposals (with financial 
details redacted) - hope those will serve as a starting point.

**Comment by adina** [comment]
Assigned to @jduckles

**Comment by jduckles** [comment]
Closing as there is a PR addressing this #23
