### ISSUE TITLE
Volunteers for communications subcommittee

### ISSUE THREAD

**Issue by adina** [swcarpentry/communications#13]
Reference https://github.com/adina/communications/issues/5

@iglpdc @LJWilliams @swaldman3 @adina

**Comment by adina** [comment]
Adding @qingpeng @amybrown

**Comment by adina** [comment]
Recruiting Bob!  @devbioinfoguy

**Comment by jduckles** [comment]
I'll lurk on this subcommittee to report back to Development and Partnerships.
