### ISSUE TITLE
Collecting existing communications materials

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/communications#2]
Please add links as comments on this issue for talks, posters, slides, etc.

**Comment by adina** [comment]
Three things I'd like to coordinate:

1)  Official SWC flyer for advertising events - a template of organizers to attract attention (@jduckles?)
2)  Slidedeck explaining our mission and vision as well as our impact (e.g., to present to potential future supporters) (@gvwilson to send examples)
3)  Text for how we might be included in future funding opportunities (e.g., if you were to include us in proposal) (@adina will do)

Looking for volunteers to help!

**Comment by iglpdc** [comment]
Hi @adina,

@amyrbrown, @katyhuff, @tracykteal, and I have been brainstorming on this [etherpad](https://datacarpentry.etherpad.mozilla.org/36) on how to organize this repo. I have some commits done, mostly README files, that I will try to push tomorrow (unless yet another blizzard hits the East Coast and cancels everything...)

**Comment by adina** [comment]
@iglpdc Thanks for letting me know.  Happy to have anyone take charge of any of these efforts as well, didn't mean to step on toes!

**Comment by iglpdc** [comment]
@adina, no worries! There is a lot of work to do here...

**Comment by jduckles** [comment]
@adina not sure why you were thinking of me there. :confused:

**Comment by jiffyclub** [comment]
Linking to my talk from the Digital Demography conference in 2014: https://github.com/jiffyclub/digital-demography-2014

**Comment by iglpdc** [comment]
I made some changes the README file in #4. Please take a look.

**Comment by adina** [comment]
Looks like these materials are added.  Closing this issue.
