### ISSUE TITLE
Create a mailing list for communications.

### ISSUE THREAD

**Issue by adina** [swcarpentry/communications#27]

**Comment by r-gaia-cs** [comment]
I can do it when I get home tonight. `communications@lists.software-carpentry.org`?

**Comment by adina** [comment]
Thats perfect thanks!

**Comment by r-gaia-cs** [comment]
@adina Done.

Could you ask people to subscribe at http://lists.software-carpentry.org/mailman/listinfo/communications_lists.software-carpentry.org? If you email me the list of email address I can subscribe them.

**Comment by adina** [comment]
@iglpdc @jduckles @amyrbrown @swaldman3 @LJWilliams @amyrbrown @czterybity - Could you please sign up for mailing list at http://lists.software-carpentry.org/mailman/listinfo/communications_lists.software-carpentry.org?  Thanks!

**Comment by swaldman3** [comment]
Done :-)

**Comment by r-gaia-cs** [comment]
@adina Can you close this?
