### ISSUE TITLE
Review of grant text

### ISSUE THREAD

**Issue by adina** [swcarpentry/communications#28]
Need volunteers to help review @jduckles nice grant text.  @adina can help.  https://github.com/swcarpentry/communications/blob/master/grant-boilerplate/grant_prose.md

**Comment by swaldman3** [comment]
I can't seem to leave inline comments (permissions issue?), but I wonder whether it's worth putting inline citations rather than just the list of references at the end. Perhaps only appropriate for some funding streams, but may give more of a feeling of the precepts of SWC being evidence-backed.

**Comment by adina** [comment]
I can't figure out how to turn on notes here @jduckles any idea?

**Comment by wking** [comment]
On Fri, Mar 20, 2015 at 10:00:39AM -0700, adina wrote:
> I can't figure out how to turn on notes here @jduckles any idea?

You can't make per-line comments on the file in the repository, but
you can go back and make per-line comments in the PR (#23) that landed
grant_prose.md, or the commit that landed the line you want to comment
on [1].

[1]: https://github.com/swcarpentry/communications/pull/23/commits

**Comment by adina** [comment]
@wking Thank you!

**Comment by wking** [comment]
On Fri, Mar 20, 2015 at 10:04:07AM -0700, W. Trevor King wrote:
> You can't make per-line comments on the file in the repository, but
> you can go back and make per-line comments in the PR (#23) that
> landed grant_prose.md, or the commit that landed the line you want
> to comment on [1].

If you want an easy way to find that commit from the in-repo file, you
can use “blame”.  E.g. [1] to [2] to [3], to comment.

[1]: https://github.com/swcarpentry/communications/blob/master/grant-boilerplate/grant_prose.md
[2]: https://github.com/swcarpentry/communications/blame/master/grant-boilerplate/grant_prose.md
[3]: https://github.com/swcarpentry/communications/commit/c5d29168df7d9542a9979a7f20eddcfde5cc7ac9
