### ISSUE TITLE
Proofreading request of SWC material from Greg

### ISSUE THREAD

**Issue by adina** [swcarpentry/communications#29]
In email to communications list:

The repository https://github.com/swcarpentry/slideshows contains slide decks about Software Carpentry.  Two of these - "Introducing Software Carpentry" and "Creating a Workshop Website" - are finished (for now), and have voiceovers - please see http://swcarpentry.github.io/slideshows/introducing-software-carpentry/index.html and http://swcarpentry.github.io/slideshows/creating-website/index.html. I'd be very grateful if members of this list could proof-read the others - in particular:

* https://github.com/swcarpentry/slideshows/blob/gh-pages/best-practices/index.html is based on our "Best Practices" paper

* https://github.com/swcarpentry/slideshows/blob/gh-pages/hosting-workshop/index.html explains how to host a workshop

* https://github.com/swcarpentry/slideshows/blob/gh-pages/teaching-tips/index.html is some teaching tips - it needs to be updated to reflect http://swcarpentry.github.io/training-course/tips/, which is where I'm collecting teaching tips for instructor training

I'm going to have some time Thursday/Friday next week for editing, so if you can submit PRs or file comments or something between now and Wednesday, it would be a big help.

**Comment by adina** [comment]
@gvwilson  What's the best way to comment on this?  I'm trying to figure out how to turn notes on in the repo but can't find the magic button.

**Comment by gvwilson** [comment]
I think you have to send a pull request - I don't know of a way to 
comment on a doc without one.

**Comment by wking** [comment]
On Fri, Mar 20, 2015 at 10:34:31AM -0700, Greg Wilson wrote:
> I think you have to send a pull request - I don't know of a way to
> comment on a doc without one.

You can comment on the commits that landed the text you're talking
about [1].

[1]: https://github.com/swcarpentry/communications/issues/28#issuecomment-84073063

**Comment by gvwilson** [comment]
Close as stale?
