### ISSUE TITLE
Sort out openbadge badges

### ISSUE THREAD

**Issue by swaldman3** [swcarpentry/communications#37]
The badges at site/img/badges currently have two different fonts in use.
The source files for them (currently in PR #36) are in Adobe's idea of a SVG file, which doesn't seem to match the rest of the world's opinion as to what the standard is ;-) Consequently they render wrongly in Inkscape and Firefox, and probably other things.

Some general fixup for consistency and for usable source files is needed. Please assign to me.

**Comment by gvwilson** [comment]
Just invited you to the @swcarpentry group - once you accept, we can 
assign this one to you.
Thanks,
@gvwilson

**Comment by swaldman3** [comment]
@gvwilson Thanks :-)
