### ISSUE TITLE
Permissions for this repo

### ISSUE THREAD

**Issue by adina** [swcarpentry/communications#39]
I don't have write access on this repo and it would be helpful if I could get it.

**Comment by adina** [comment]
Perfect, I thought I was going crazy.

**Comment by gvwilson** [comment]
The two aren't mutually exclusive :-)

**Comment by jiffyclub** [comment]
I've made a communications team with you and most of the other communications members on it. I couldn't find a GitHub ID for Simon Waldman.

**Comment by jiffyclub** [comment]
Nevermind, found it! Everyone should be on the team now.
