### ISSUE TITLE
Which would be the best place to archive old grants and presentations? 

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/communications#6]
If we are going to use this repo to store texts that can be reused to create new materials, which will be the place to store past grant applications, presentations, and alike?

In my view for this repo, I think that we should keep here stuff that we can reuse. E.g. a short text explaining how past record or another the state of the art in teaching software to scientists are more useful than a past application that may be outdated or written in an uncommon format.

However, past applications have a lot of effort on them that is worth keeping. So, which will be the best way to store those in the long term?

- an always-open issue in this repo, as #2 ,
- a wiki page where people can add new links,
- subfolders in this repo, like `2014-01-22-nsf-grant`?

Thoughts?

**Comment by wking** [comment]
On Fri, Feb 20, 2015 at 10:41:35AM -0800, Ivan Gonzalez wrote:
> - a wiki page where people can add new links,

This makes the most sense to me.  Git versioning for the old marterial
(or links to it) without cluttering the main repository.

**Comment by adina** [comment]
Ivan,

Do you have any objection to be the lead on communications and getting this
repo in shape?

Thanks,
Adina

**Comment by kynan** [comment]
+1 for wiki

**Comment by iglpdc** [comment]
Ok, be wiki!

**Comment by iglpdc** [comment]
See https://github.com/swcarpentry/communications/wiki/Archive-of-links-to-past-grants
